name: "The Second Page"
description: 'The Second Page is a storytelling radio show hosted by Harris Lapiroff.'
url: http://makesomethingeveryday.com/secondpage
safe: true
paginate: 3
exclude: Gemfile Gemfile.lock CNAME new log
baseurl: /secondpage
